## Configuraci贸n de Spring
spring:
  application:
    name: ms-books-catalogue
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/catalogue
    username: ${DATABASE_USERNAME:books}
    password: ${DATABASE_PASSWORD:books123}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  elasticsearch:
    client:
      reactive:
        enabled: false

# Propiedades personalizadas para la conexi贸n a Elasticsearch
elasticsearch:
  host: ${ELASTICSEARCH_HOST:localhost}
  port: ${ELASTICSEARCH_PORT:9200}
  scheme: ${ELASTICSEARCH_SCHEME:http}

## Configuraci贸n de Instancia
server:
  port: 8088

## Configuraci贸n del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-books-catalogue
