## Configuración de Spring
spring:
  main:
    web-application-type: servlet
  application:
    name: ms-books-catalogue
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: books
    password: books123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  elasticsearch:
    rest:
      uris: http://localhost:9200
    client:
      reactive:
          enabled: false

## Configuración de Instancia
server:
  port: 8088

## Configuración del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-books-catalogue

